services:
  - type: web
    name: ho-n-ti-n
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: VITE_FCM_VAPID_KEY
        sync: false
    healthCheckPath: /
