/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const VIETNAMESE_BANKS = [
  { code: 'VCB', name: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)' },
  { code: 'BIDV', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)' },
  { code: 'VTB', name: 'Ngân hàng TMCP Bảo Việt (BAOVIET Bank)' },
  { code: 'TCB', name: 'Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)' },
  { code: 'VPB', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)' },
  { code: 'CTG', name: 'Ngân hàng TMCP Công thương Việt Nam (VietinBank)' },
  { code: 'MB', name: 'Ngân hàng TMCP Quân đội (MB Bank)' },
  { code: 'TPB', name: 'Ngân hàng TMCP Tiên Phong (TPBank)' },
  { code: 'ACB', name: 'Ngân hàng TMCP Á Châu (ACB)' },
  { code: 'SHB', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)' },
  { code: 'HDB', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh (HDBank)' },
  { code: 'MSB', name: 'Ngân hàng TMCP Hàng hải Việt Nam (MSB)' },
  { code: 'OCB', name: 'Ngân hàng TMCP Phương Đông (OCB)' },
  { code: 'VIB', name: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)' },
  { code: 'NCB', name: 'Ngân hàng TMCP Quốc Dân (NCB)' },
  { code: 'SCB', name: 'Ngân hàng TMCP Sài Gòn (SCB)' },
  { code: 'PGB', name: 'Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)' },
  { code: 'EIB', name: 'Ngân hàng TMCP Xuất nhập khẩu Việt Nam (EximBank)' },
  { code: 'ABB', name: 'Ngân hàng TMCP An Bình (ABBank)' },
  { code: 'BAC', name: 'Ngân hàng TMCP Bắc Á (BacABank)' },
  { code: 'VAB', name: 'Ngân hàng TMCP Việt Á (VietABank)' },
  { code: 'NAB', name: 'Ngân hàng TMCP Nam Á (NamABank)' },
  { code: 'SGB', name: 'Ngân hàng TMCP Sài Gòn Công thương (Saigonbank)' },
  { code: 'KLB', name: 'Ngân hàng TMCP Kiên Long (Kienlongbank)' },
  { code: 'LPB', name: 'Ngân hàng TMCP Bưu điện Liên Việt (LienVietPostBank)' },
  { code: 'SEAB', name: 'Ngân hàng TMCP Đông Nam Á (SeABank)' },
  { code: 'UOB', name: 'Ngân hàng United Overseas Bank Việt Nam (UOB)' },
  { code: 'CIT', name: 'Ngân hàng TNHH MTV CITibank Việt Nam (Citibank)' },
  { code: 'HSBC', name: 'Ngân hàng TNHH MTV HSBC Việt Nam (HSBC)' },
  { code: 'SC', name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam (Standard Chartered)' },
  { code: 'CKB', name: 'Ngân hàng TNHH MTV Woori Việt Nam (Woori Bank)' },
  { code: 'KEB', name: 'Ngân hàng TNHH MTV KE B Hana Việt Nam (KEB Hana Bank)' },
  { code: 'SHBVN', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam (Shinhan Bank)' },
  { code: 'AGB', name: 'Ngân hàng TNHH MTV Đại Á (Daiwa Bank)' },
  { code: 'ICB', name: 'Ngân hàng TNHH MTV CIMB Việt Nam (CIMB)' },
  { code: 'MBG', name: 'Ngân hàng TNHH MTV Public Bank Việt Nam (Public Bank)' },
  { code: 'IND', name: 'Ngân hàng Indovina Bank (Indovina)' },
  { code: 'VRB', name: 'Ngân hàng Liên doanh Việt Nga (VRB)' },
  { code: 'COOP', name: 'Ngân hàng Hợp tác xã Việt Nam (Co-opBank)' },
  { code: 'BAB', name: 'Ngân hàng TMCP Bắc Bộ (BacABank)' },
  { code: 'DLB', name: 'Ngân hàng TMCP Đông Dương (DongIndus Bank)' },
  { code: 'GDB', name: 'Ngân hàng TMCP Dầu khí Toàn cầu (Global Petroleum Bank)' },
  { code: 'KLBVN', name: 'Ngân hàng TNHH MTV Kasikorn Việt Nam (Kasikorn Bank)' },
  { code: 'MHB', name: 'Ngân hàng TMCP Mizuho Việt Nam (Mizuho Bank)' },
  { code: 'NMH', name: 'Ngân hàng TNHH MTV NMH Việt Nam (BNP Paribas)' },
  { code: 'BNP', name: 'Ngân hàng BNP Paribas' },
];
